In [11]:
# Setting up a custom stylesheet in IJulia
file = open("style.css") # A .css file in the same folder as this notebook file
styl = readall(file) # Read the file
HTML("$styl") # Output as HTML

HTML{ASCIIString}("<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans:100,300,400,500,700,800,900,100italic,300italic,400italic,500italic,700italic,800italic,900italic' rel='stylesheet' type='text/css'>\n<link href='http://fonts.googleapis.com/css?family=Arvo:400,700,400italic' rel='stylesheet' type='text/css'>\n<link href='http://fonts.googleapis.com/css?family=PT+Mono' rel='stylesheet' type='text/css'>\n<link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>\n<link href='http://fonts.googleapis.com/css?family=Philosopher:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\n\n<style>\n\n@font-face {\n    font-family: \"Computer Modern\";\n    src: url('http://mirrors.ctan.org/fonts/cm-unicode/fonts/otf/cmunss.otf');\n}\n\n#notebook_panel { /* main background */\n    background: #ddd;\n    color: #000000;\n}\n\n\n\n/* Formatting for header cells */\n.text_cell_render h1 {\n    font-family: 'Philosopher', sans-serif;\n    font-weight: 400;\n    font-size: 2.2em;\n    line-height: 100%;\n    color: rgb(0, 80, 120);\n    margin-bottom: 0.1em;\n    margin-top: 0.1em;\n    display: block;\n}\t\n.text_cell_render h2 {\n    font-family: 'Philosopher', serif;\n    font-weight: 400;\n    font-size: 1.9em;\n    line-height: 100%;\n    color: rgb(200,100,0);\n    margin-bottom: 0.1em;\n    margin-top: 0.1em;\n    display: block;\n}\t\n\n.text_cell_render h3 {\n    font-family: 'Philosopher', serif;\n    margin-top:12px;\n    margin-bottom: 3px;\n    font-style: italic;\n    color: rgb(94,127,192);\n}\n\n.text_cell_render h4 {\n    font-family: 'Philosopher', serif;\n}\n\n.text_cell_render h5 {\n    font-family: 'Alegreya Sans', sans-serif;\n    font-weight: 300;\n    font-size: 16pt;\n    color: grey;\n    font-style: italic;\n    margin-bottom: .1em;\n    margin-top: 0.1em;\n    display: block;\n}\n\n.text_cell_render h6 {\n    font-family: 'PT Mono', sans-serif;\n    font-weight: 300;\n    font-size: 10pt;\n    color: grey;\n    margin-bottom: 1px;\n    margin-top: 1px;\n}\n\n.CodeMirror{\n        font-family: \"PT Mono\";\n        font-size: 100%;\n}\n\n</style>\n\n")

# Functions in Julia II

<h2>In this lecture</h2>

- [Outcome](#Outcome)
- [One-line function definition](#One-line-function-definition)
- [Multi-line function definition](#Multi-line-function-definition)
- [Functions with multiple methods](#Functions-with-multiple-methods)


<hr>
<h2>Outcome</h2>

After this lecture, you will be able to: 

- Define a function using the "functionname(varlist) = ..." one-line syntax
- Define a function using the "function name(varlist) ... end" multiline syntax
- Define an additional method for an existing user-defined function
- Specify types for input values in a user-defined function
- Use workspace() to clear the notebook of all values so that function signatures can be redefined.

[Back to the top](#In-this-lecture)

<h2>One-line function definition</h2>

This has an extremely simple form. For example:

In [1]:
myfunc(firstvar) = 20*firstvar  

myfunc (generic function with 1 method)

In [2]:
myfunc(5)

100

The rules are for defining one-line function are: 
- the name of the function must be a valid variable name (in this case "myfunc" is the name)
- the arguments of the function must be valid variable names
- the argument must be in parentheses (and as we'll see, multiple arguments must be separated by values)
- the name, with arguments in parentheses goes on the left of an assignment
- the code for evaluating the function goes on the right.

By the way, it's not quite accurate that the code must always fit on one line---it must be a single statement, but so-called compound statements are often written with line breaks, to help the human reader. We will not be using compound statements in one-line functions in this course.

In [2]:
myfunc(333.2222)       # then we just call it like any other function

6664.4439999999995

Here is an illustration of a two-argument function:

In [8]:
addxtoy(x,y) = 
    x + y   # not supposed to be useful! it just shows how the job is done

addxtoy (generic function with 1 method)

In [6]:
addxtoy(33, -22.2)     # mixed types: illustrates that for quick and dirty code, we can (mostly) ignore types

10.8

[Back to the top](#In-this-lecture)

<h2>Multi-line function definition</h2>

Let's face it, computing should not be all be done with one-liners. Julia supplies the following syntax for functions that take up multiple lines:

In [6]:
function nextfunc(a, b, c)  # this line names your function and specifies the inputs
    a*b + c                # here go your (usually quite a few) lines

    #  ... just illustrating the possiblity of using white space and additional comments 
end


nextfunc (generic function with 1 method)

In [7]:
nextfunc(7,5,3)           # again, just call it like any other function

38

To illustrate multi-line functions a bit more, here's a useful device for debugging: a line inside a function that gives you the value and the type of a variable. 

It relies on the escape character "$" in strings, which you recall DOESN'T create a dollar sign, but instead modifies how the string is built.


In [9]:
function showdebugprintln(testvar)
    println("inside the showdebubprint() now")   #this line announces where the report is coming from
    println("The type of testvar is $(typeof(testvar)) and the value of testvar is $testvar")
    #                  and this line reports what value, and hence what type, testvar actually has here
end
    

showdebugprintln (generic function with 1 method)

In [10]:
a = ['1',2.]
showdebugprintln(a)

inside the showdebubprint() now
The type of testvar is Array{Any,1} and the value of testvar is Any['1', 2.0]


[Back to the top](#In-this-lecture)

<h2>Functions with multiple methods</h2>

As we saw in Lecture 8, many code bodies can share one function name. Julia knows which of them is relevant via the type signature. The type signature is simply the list of types of all the variables that are used to call the function. 

Here is a function that basically parallels the cos function.

In [11]:
mycos(x) = cos(x)

mycos (generic function with 1 method)

In [ ]:
mycos(.7)  # standard value of cos (angle in radians, of course)

Now we extend mycos() by providing a function for computing the cosine from the hypotenuse and adjacent side: 

In [ ]:
mycos(adj, hyp) = adj/hyp

In [24]:
mycos(12, 13)  # the cosine of the larger angle in a standard 5, 12, 13 triangle

0.9230769230769231

In [25]:
methods(mycos)  #Check this carefully!

# 2 methods for generic function "mycos":
mycos(x) at In[11]:1
mycos(hyp, adj) at In[23]:1

Again, methods() is your friend. Note especially that each method is given in terms of its input variables.

As with every user-defined function, it is easy for these to go wrong. Suppose we want to make sure the mycos(x) is never called for integer values. We can require the input to be Float64 as follows:

In [26]:
mycos(thet::Float64) = cos(thet)   # note  the use of :: to force Julia to check the type 

mycos (generic function with 3 methods)

However, there are now three methods, and integers can still be passed (check this for yourself). We actually intended to replace mycos(x) with mycos(thet::Float64). To do so, first we must clear the old version. Unfortunately, the only way to clear a notebook is to clear everything, by using workspace(). 

Everything is cleared, so we have to redefine not only mycos(x) but also mycos(adj, hyp):

In [45]:
workspace()        # no argument, please!  
#        ... clears all the results
mycos(thet::Float64) = cos(thet)  # so passing mycos() an integer will now cause Julia to throw an error
mycos(hyp, adj)      = adj/hyp

mycos (generic function with 1 method)

In [47]:
mycos(1)     # ... this shouldn't work now ...

LoadError: LoadError: MethodError: `mycos` has no method matching mycos(::Int64)
while loading In[47], in expression starting on line 1

In [11]:
?\

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Array{Float64,1}:
  6.5
 -7.0

julia> inv(A) * x
2-element Array{Float64,1}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Array{Float64,1}:
 32.0
 18.0

julia> A * X == B
true
```

---

```
(\)(F::QRSparse, B::StridedVecOrMat)
```

Solve the least squares problem $\min\|Ax - b\|^2$ or the linear system of equations $Ax=b$ when `F` is the sparse QR factorization of $A$. A basic solution is returned when the problem is underdetermined.

# Examples

```jldoctest
julia> A = sparse([1,2,4], [1,1,1], [1.0,1.0,1.0], 4, 2)
4×2 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  1.0
  [4, 1]  =  1.0

julia> qr(A)\fill(1.0, 4)
2-element Array{Float64,1}:
 1.0
 0.0
```


In [12]:
3 \ 6

2.0

In [14]:
6\3

0.5

[Back to the top](#In-this-lecture)

In [15]:
5\10

2.0

In [16]:
2\1

0.5

In [17]:
methods(\)

# 158 methods for generic function "\":
[1] \(a::Float16, b::Float16) in Base at float.jl:398
[2] \(x::Number, A::LinearAlgebra.UpperTriangular) in LinearAlgebra at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/LinearAlgebra/src/triangular.jl:868
[3] \(x::Number, A::LinearAlgebra.UnitUpperTriangular) in LinearAlgebra at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/LinearAlgebra/src/triangular.jl:871
[4] \(x::Number, A::LinearAlgebra.LowerTriangular) in LinearAlgebra at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/LinearAlgebra/src/triangular.jl:868
[5] \(x::Number, A::LinearAlgebra.UnitLowerTriangular) in LinearAlgebra at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/LinearAlgebra/src/triangular.jl:871
[6] \(A::Number, B::AbstractArray) in Base at arraymath.jl:52
[7] \(A::Union{BitArray{2}, BitArray{1}}, B::Union{BitArray{2}, BitArray{1}}) in Base at bitarray.jl:1122
[8] \(A::LinearAlgebra.Adjoint{T,#s662} where #s662<:(LinearAlgebra.LU{T,#s661} where #s661<:(Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where T)), B::LinearAlgebra.Adjoint{T,#s660} where #s660<:Union{DenseArray{T,1}, DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReinterpretArray{T,1,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,1,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.Multiplicative

In [18]:
60 \ 5040

84.0

In [19]:
addone(x::Int64) = x+1

addone (generic function with 1 method)

In [20]:
addone(10.)

MethodError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(!Matched::Int64) at In[19]:1

In [21]:
addone(20*1.0)

MethodError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(!Matched::Int64) at In[19]:1

In [22]:
ceil(1.2)*10

20.0

In [23]:
ceil(1.2)

2.0

In [24]:
a,b = 1,2

b = a

a = b

1

In [25]:
function test(input)
  println("$input"^2)
end

test(2)

22


In [33]:
add2(x,y) = x+y
println(add2(5, 7))

12


In [34]:
function coordinates(x, y=0, z=0)
  println("($x, $y, $z)")
end

coordinates (generic function with 3 methods)

In [35]:
coordinates(1,2)

(1, 2, 0)


In [36]:
coordinates(1,0,2)

(1, 0, 2)


In [37]:
coordinates(1,0)

(1, 0, 0)


In [ ]:
coordinates()