# Week 1 - Graded Quiz

In [1]:
12 == 

ErrorException: syntax: type declarations on global variables are not yet supported

In [3]:
typeof(println("$(2*6)"))

12


Nothing

In [5]:
12 == println("$(2*6)")

12


false

In [7]:
(2^3)^2-500

-436

In [8]:
12 == (2^3)^2-500

false

In [9]:
12 == 2^3^2-500

true

In [10]:
2^3^2-500

12

In [11]:
typeof(2^3^2-500)

Int64

In [12]:
2^2^1^5+2^3

12

In [13]:
12 == 2^2^1^5+2^3

true

In [14]:
5 - 7 * 2 + 4

-5

In [15]:
5-7*(2+4)

-37

In [16]:
(5 - 7) * 2 + 4

0

In [17]:
5 - (7 * 2) + 4

-5

In [18]:
1 + 3 < 5 && 2^2 === 4.0

false

In [27]:
0 == 0.0

true

In [30]:
0 === 0

true

In [26]:
?===

search: === == !==



```
===(x,y) -> Bool
≡(x,y) -> Bool
```

Determine whether `x` and `y` are identical, in the sense that no program could distinguish them. First the types of `x` and `y` are compared. If those are identical, mutable objects are compared by address in memory and immutable objects (such as numbers) are compared by contents at the bit level. This function is sometimes called "egal". It always returns a `Bool` value.

# Examples

```jldoctest
julia> a = [1, 2]; b = [1, 2];

julia> a == b
true

julia> a === b
false

julia> a === a
true
```


In [36]:
x = 5
(x ≥ 5.0) && (x < 7.0)

true

In [40]:
true && ((false && false) || true)

true

In [47]:
true && (false && (false || true))

false

In [50]:
((true && false) && false) || true

true

In [49]:
(true && false) && (false || true)

false

In [51]:
a = 2
b = 3

matrix = Array{Float64,2}(undef, a, b)

2×3 Array{Float64,2}:
 2.22538e-314  2.22538e-314  2.22538e-314
 2.22538e-314  2.22538e-314  2.30712e-314

In [52]:
data = [1.6800483  -1.641695388; 
        0.501309281 -0.977697538; 
        1.528012113 0.52771122;
        1.70012253 1.711524991; 
        1.992493625 1.891000015;
        2.706075824 -0.463427794;
        2.994931927 -0.443566619;
        3.491852811 -1.275179133;
        3.501191722 -0.690499597;
        4.459924502 -5.516130799;
        4.936965851 -6.001703074;
        5.023289852 -8.36416901;
        5.04233698 -7.924477517;
        5.50739285 -10.77482371;
        5.568665171 -10.9171878]

15×2 Array{Float64,2}:
 1.68005    -1.6417
 0.501309   -0.977698
 1.52801     0.527711
 1.70012     1.71152
 1.99249     1.891
 2.70608    -0.463428
 2.99493    -0.443567
 3.49185    -1.27518
 3.50119    -0.6905
 4.45992    -5.51613
 4.93697    -6.0017
 5.02329    -8.36417
 5.04234    -7.92448
 5.50739   -10.7748
 5.56867   -10.9172

In [53]:
data[1,:] # first row

2-element Array{Float64,1}:
  1.6800483
 -1.641695388

In [58]:
data[:,1] # first column

15-element Array{Float64,1}:
 1.6800483
 0.501309281
 1.528012113
 1.70012253
 1.992493625
 2.706075824
 2.994931927
 3.491852811
 3.501191722
 4.459924502
 4.936965851
 5.023289852
 5.04233698
 5.50739285
 5.568665171

In [57]:
data[2,:] # second row

2-element Array{Float64,1}:
  0.501309281
 -0.977697538

In [77]:
function coordinates(x, y, z)
  if x==0 & y==0 & x==z
    println("origin")
  else
    println("($x, $y, $z)")
  end
end

coordinates(0,0,2)
coordinates(0,0,0)

(0, 0, 2)
origin


In [60]:
x,y,z = 1,2,3


UndefVarError: UndefVarError: coordinates not defined

In [69]:
true && false

false

In [70]:
ξ # \xi

UndefVarError: UndefVarError: ξ not defined

In [78]:
⊻ #\xor

xor (generic function with 15 methods)

In [79]:
a, b = 2, 3           
function f(x)  
  b = 5 # local assignment
  a*x + b
end
f(7), b # this b is not changed by the function

(19, 3)

In [82]:
function f(x)
  return 2x
  println(3x) # not printed because after the return
end

f(5)

10